package:
  name: dftbox
  version: "0.1.0"

source:
  path: ..

build:
  noarch: python
    #  script: {{PYTHON}} -m pip install .  --no-deps -vv
    


requirements:
  build:
    - python >=3.9,<3.13
    - pip
    - setuptools
    - wheel
  host:
    - python >=3.9,<3.13
    - setuptools
    - pip
    - wheel 
  run:
    - python >=3.9,<3.13
    - numpy >=1.26
    - matplotlib
    - scipy
    - h5py
    - pyyaml

about:
  summary: Toolkit for managing and postprocessing VASP DFT calculations on HPC/SLURM clusters
  license: MIT

